### ISSUE TITLE
Error When Running chi3d Dataset

### ISSUE THREAD

**Issue by Zavianx** [liangxuy/ReGenNet#4]
I encountered an error when trying to train the chi3d dataset. Here is the relevant error message:
![image](https://github.com/user-attachments/assets/306550ab-077f-4804-ae92-decf22a53079)
The training command I used is: `python -m train.train_mdm --setting cmdm --save_dir save/cmdm/chi3d --dataset chi3d --data_path datasets/chi3d/chi3d_smplx_train.h5 --pose_rep rot6d --cond_mask_prob 0 --num_person 2 --layers 8 --num_frames 60  --overwrite --arch online`，Could you please provide guidance on how to resolve this issue?

**Comment by liangxuy** [comment]
Hi, please add `--body_model smplx` and `--num_frames 150` for the chi3d dataset.

**Comment by Zavianx** [comment]
Thanks. I'll try it~
